// ported from @shaktool's https://code.google.com/p/beepbox/

module.exports = {
  scaleFlags: [
    [ true, false,  true, false,  true, false, false,  true, false,  true, false, false],
    [ true, false, false,  true, false,  true, false,  true, false, false,  true, false],
    [ true, false, false, false,  true,  true, false,  true, false, false, false,  true],
    [ true,  true, false,  true, false, false, false,  true,  true, false, false, false],
    [ true, false, false,  true,  true, false, false,  true, false,  true,  true, false],
    [ true, false, false,  true, false,  true,  true,  true, false, false,  true, false],
    [ true, false,  true, false,  true,  true, false,  true, false,  true, false,  true],
    [ true, false,  true,  true, false,  true, false,  true,  true, false,  true, false],
    [ true,  true, false, false,  true,  true, false,  true,  true, false,  true, false],
    [ true, false,  true,  true, false, false,  true,  true,  true, false, false,  true],
    [ true, false,  true, false,  true, false,  true, false,  true, false,  true, false],
    [ true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true,  true],
  ],
  pianoScaleFlags: [ true, false,  true, false,  true,  true, false,  true, false,  true, false,  true],
  scaleNames: ["easy :)", "easy :(", "island :)", "island :(", "blues :)", "blues :(", "normal :)", "normal :(", "flamenco :)", "flamenco :(", "enigma", "expert"],
  keyNames: ["B", "Bb", "A", "Ab", "G", "F#", "F", "E", "Eb", "D", "C#", "C"],
  keyTransposes: [23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12],
  tempoNames: ["molasses", "slow", "leisurely", "moderate", "steady", "brisk", "hasty", "fast", "strenuous", "grueling", "hyper", "ludicrous"],
  beatsMin: 3,
  beatsMax: 12,
  barsMin: 1,
  barsMax: 128,
  patternsMin: 1,
  patternsMax: 32,
  instrumentsMin: 1,
  instrumentsMax: 10,
  partNames: ["triples", "standard"],
  partCounts: [3, 4],
  noteNames: ["C", "C#", "D", "Eb", "E", "F", "F#", "G", "Ab", "A", "Bb", "B"],
  waveNames: ["triangle", "square", "pulse wide", "pulse narrow", "sawtooth", "double saw", "double pulse", "spiky", "plateau"],
  waveVolumes: [1.0, 0.5, 0.5, 0.5, 0.65, 0.5, 0.4, 0.4, 0.94],
  drumNames: ["retro", "white"],
  drumVolumes: [0.25, 1.0],
  filterNames: ["sustain sharp", "sustain medium", "sustain soft", "decay sharp", "decay medium", "decay soft"],
  filterBases: [2.0, 3.5, 5.0, 1.0, 2.5, 4.0],
  filterDecays: [0.0, 0.0, 0.0, 10.0, 7.0, 4.0],
  filterVolumes: [0.4, 0.7, 1.0, 0.5, 0.75, 1.0],
  attackNames: ["binary", "sudden", "smooth", "slide"],
  effectNames: ["none", "vibrato light", "vibrato delayed", "vibrato heavy", "tremelo light", "tremelo heavy"],
  effectVibratos: [0.0, 0.15, 0.3, 0.45, 0.0, 0.0],
  effectTremelos: [0.0, 0.0, 0.0, 0.0, 0.25, 0.5],
  chorusNames: ["union", "shimmer", "hum", "honky tonk", "dissonant", "fifths", "octaves"],
  chorusValues: [0.0, 0.02, 0.05, 0.1, 0.25, 3.5, 6],
  chorusOffsets: [0.0, 0.0, 0.0, 0.0, 0.0, 3.5, 6],
  chorusVolumes: [0.7, 0.8, 1.0, 1.0, 0.9, 0.9, 0.8],
  volumeNames: ["loudest", "loud", "medium", "quiet", "quietest", "mute"],
  volumeValues: [0.0, 0.5, 1.0, 1.5, 2.0, -1.0],
  channelVolumes: [0.27, 0.27, 0.27, 0.19],
  rhythmNames: ["standard", "triplets"],
  drumInterval: 6,
  numChannels: 4,
  drumCount: 11,
  noteCount: 37,
  maxPitch: 84,
};
