all:
	gcc -shared -o bass.so bass.c
	gcc -shared -o snare.so snare.c
	gcc -shared -o lead.so lead.c
	gcc -shared -o lead2.so lead2.c
	gcc -shared -o spread.so spread.c
	gcc -shared -o reverb.so reverb.c
